### ISSUE TITLE
raw_signal.py reads record which doesn't exist

### ISSUE THREAD

**Issue by Theo-Nelson** [Maggi-Chen/FusionSeeker#2]
Dear Maggi,

Recently I was analyzing sample DRR138513 from the European Nucleotide Archive. I received this error message while running FusionSeeker on the sorted bam output. I received the error whether running FusionSeeker with your original GitHub repo or with my fork. 

what I noticed is that the program was searching for a particular record ```record_read_chr9_GL383539v1_alt```, which has a GL number one less than the GL numbers which I do see within the directory. The image below displays this comparison.  

<img width="1585" alt="Screen Shot 2022-09-10 at 6 11 38 PM" src="https://user-images.githubusercontent.com/99562847/189503487-6d1311cc-4d08-4ecb-af32-7fd760b5f934.png">

machine details:

NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

full pipeline outputs: https://github.com/Theo-Nelson/long-read-sequencing-pipeline-examples/blob/main/long_read_rna_seq_analysis-DRR138513.ipynb

Please let me know whether this is a problem with the sample or the program. Thank you very much!

Sincerely,
Theo

**Comment by kristianunger** [comment]
Adding to this I got the same error:

Traceback (most recent call last):
  File "/home/kunger/data2/FusionSeeker/fusionseeker", line 104, in <module>
    raw_signal.detect_from_split(defusion_args.outpath,goodchrom)
  File "/data2/core-strahl-kitso/FusionSeeker/raw_signal.py", line 373, in detect_from_split
    allsplitread+=open(outpath+'raw_signal/record_read_'+chrom,'r').read().split('\n')[:-1]
FileNotFoundError: [Errno 2] No such file or directory: 'fusion_out/raw_signal/record_read_chr18'

Any hint how this can be fixed?

**Comment by yinyuanmtu** [comment]
I got the same error. Hope the developed can help solve the issue.

**Comment by nci-tech** [comment]
Same error.
