### ISSUE TITLE
Error with test to verify installation

### ISSUE THREAD

**Issue by RDorney** [Maggi-Chen/FusionSeeker#3]
Hi Maggie,
I was checking if the installation had been successful and tried to run the provided test:
**fusionseeker --bam FusionSeeker/testdata/test.bam  -o test_out/ --datatype isoseq --ref FusionSeeker/testdata/test.fa.gz**

unfortunately I only got the following error messages:
Traceback (most recent call last):
  File "./fusionseeker", line 104, in <module>
    raw_signal.detect_from_split(defusion_args.outpath,goodchrom)
  File "/opt/FusionSeeker/raw_signal.py", line 373, in detect_from_split
    allsplitread+=open(outpath+'raw_signal/record_read_'+chrom,'r').read().split('\n')[:-1]
**FileNotFoundError: [Errno 2] No such file or directory: 'test_out/raw_signal/record_read_chr20'**

I then removed the test_out/ folder to try again and instead got the same error but for record_read_chr17 (_I had not changed anything in my command_)

Traceback (most recent call last):
  File "./fusionseeker", line 104, in <module>
    raw_signal.detect_from_split(defusion_args.outpath,goodchrom)
  File "/opt/FusionSeeker/raw_signal.py", line 373, in detect_from_split
    allsplitread+=open(outpath+'raw_signal/record_read_'+chrom,'r').read().split('\n')[:-1]
**FileNotFoundError: [Errno 2] No such file or directory: 'test_out/raw_signal/record_read_chr17'**

Any suggestions on how to resolve this error would be much appreciated.

**Other notes**
I had set up my environment with Anaconda3 not Anaconda2, but I do not imagine this would be the cause of the issue given the dependancy on Python 3

**Comment by RDorney** [comment]
I was able to resolve the error by creating empty files with the name of the record_read_chr17 and record_read_chr20

**Comment by RDorney** [comment]
after checking the testdata/ folder to check confident_genefusion.txt, I now realise this wasn't right because the fusion was meant to be between chr17 and chr20. there could be an error in how the raw_signal is generated???
