### ISSUE TITLE
Error with testing installation

### ISSUE THREAD

**Issue by RDorney** [Maggi-Chen/FusionSeeker#4]
Hi @Maggi-Chen, I'm use the test supplied on the github page and I've run into the below errors

```
(fusions) ryleyd@minion:/data2/ryleyd/FusionSeeker$ ./fusionseeker --bam testdata/test.bam  -o test_out/ --datatype isoseq --ref testdata/test.fa.gz
mkdir: cannot create directory ‘test_out/raw_signal/’: File exists
samtools: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
[M::mm_idx_gen::4.146*1.36] collected minimizers
[M::mm_idx_gen::5.733*1.81] sorted minimizers
[M::main::5.733*1.81] loaded/built the index for 25 target sequence(s)
[M::mm_mapopt_update::6.344*1.73] mid_occ = 238
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 25
[M::mm_idx_stat::6.754*1.69] distinct minimizers: 29743272 (78.93% are singletons); average occurrences: 1.691; average spacing: 2.937; total length: 147701953
[ERROR] failed to write the results: Broken pipe
samtools: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
mkdir: cannot create directory ‘test_out/poa_workspace/raw_signal/’: File exists
Traceback (most recent call last):
  File "./fusionseeker", line 119, in <module>
    poa.polish_bp(defusion_args.outpath,goodchrom,defusion_args.ref,defusion_args.datatype,True)
  File "/data2/ryleyd/FusionSeeker/poa.py", line 65, in polish_bp
    raw_signal.get_raw_signal(outpath+'poa_workspace/allpoaseq.bam',outpath+'poa_workspace/',chrom,recordseq=False)
  File "/data2/ryleyd/FusionSeeker/raw_signal.py", line 164, in get_raw_signal
    bam=pysam.AlignmentFile(bampath,'rb')
  File "pysam/calignmentfile.pyx", line 311, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4929)
  File "pysam/calignmentfile.pyx", line 480, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:6905)
OSError: file `b'test_out/poa_workspace/allpoaseq.bam'` not found
```

**Comment by RDorney** [comment]
looking into this part of the error
```
samtools: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
```
I learnt that somehow conda had installed an earlier version of samtools. I had installed it earlier with the conda install command on the github page, so I'm not sure why this has happened. but by installing samtools 1.9 I was able to resolve the error.
apologies
