### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by yinyuanmtu** [Maggi-Chen/FusionSeeker#9]
This error happened when I run the command:
Traceback (most recent call last):
  File "/media/yinyuan/Data/FusionSeeker/./fusionseeker", line 104, in <module>
    raw_signal.detect_from_split(defusion_args.outpath,goodchrom)
  File "/media/yinyuan/Data/FusionSeeker/raw_signal.py", line 373, in detect_from_split
    allsplitread+=open(outpath+'raw_signal/record_read_'+chrom,'r').read().split('\n')[:-1]
FileNotFoundError: [Errno 2] No such file or directory: 'fusionseeker_out/raw_signal/record_read_Chr08'

**Comment by nci-tech** [comment]
Same error message.
Traceback (most recent call last):
  File "./fusionseeker", line 104, in <module>
    raw_signal.detect_from_split(defusion_args.outpath,goodchrom)
  File "/FusionSeeker/raw_signal.py", line 373, in detect_from_split
    allsplitread+=open(outpath+'raw_signal/record_read_'+chrom,'r').read().split('\n')[:-1]
FileNotFoundError: [Errno 2] No such file or directory: '/fusionseeker_out/raw_signal/record_read_KI270731.1'
